repos:
  - hooks:
      - args: [--remove-all-unused-imports, --in-place]
        id: autoflake
    repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: debug-statements
      - id: check-toml
      - id: trailing-whitespace
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: name-tests-test
        args: ["--django"]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - args:
          - -v
        id: black
        require_serial: true
        name: black
        entry: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - args:
          - --py312-plus
        id: pyupgrade
